version: '3.9'
services:
  redis:
    container_name: redis_server
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
